# Generated by Django 5.2.1 on 2025-11-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0002_anchoruser_created_at_and_more'),
        ('polaris', '0014_auto_20220211_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polaris.transaction')),
                ('funding_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('wallet', 'Wallet Transfer'), ('cash', 'Cash Agent')], default='bank', max_length=16)),
            ],
            bases=('polaris.transaction',),
        ),
    ]
