# Generated by Django 5.2.1 on 2025-11-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0003_anchortransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchortransaction',
            name='external_agent_id',
            field=models.CharField(blank=True, help_text='Agent identifier from BuntuPay/Nest system', max_length=255, null=True),
        ),
    ]
