# Generated by Django 5.2.1 on 2025-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0004_anchortransaction_external_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayout',
            name='agent',
        ),
    ]
